# Generated by Django 2.0.2 on 2018-02-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardGold', models.IntegerField()),
                ('rewardWood', models.IntegerField()),
                ('rewardIron', models.IntegerField()),
                ('level', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('crew', models.IntegerField()),
                ('cannon', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('crew', models.IntegerField()),
                ('level', models.IntegerField()),
                ('cannon', models.IntegerField()),
                ('life', models.IntegerField()),
                ('currentActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pirateWarApp.Activity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pirateWarApp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pirateWarApp.Category'),
        ),
    ]
