# Generated by Django 2.0.2 on 2018-03-26 09:03

import datetime

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('pirateWarApp', 'Category')
    for n in ['Defense', 'Attack', 'Shipping']:
        cat = Category(name=n)
        cat.save()


def create_activities(apps, schema_editor):
    Activity = apps.get_model('pirateWarApp', 'Activity')
    Category = apps.get_model('pirateWarApp', 'Category')
    for i in range(1, 4):
        for l in range(1, 4):
            activity = Activity(category=Category.objects.get(pk=i), rewardGold=l * 20, rewardWood=l * 20,
                                rewardIron=l * 20, level=l,
                                duration=datetime.timedelta(seconds=l*10))
            activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pirateWarApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
        migrations.RunPython(create_activities)
    ]
