# Generated by Django 2.0.2 on 2018-03-26 09:03

from django.db import migrations
import datetime


def create_categories(apps, schema_editor):
    Category = apps.get_model('pirateWarApp', 'Category')
    for n in ['Defense', 'Attack', 'Shipping']:
        cat = Category(name=n)
        cat.save()


def create_activities(apps, schema_editor):
    Activity = apps.get_model('pirateWarApp', 'Activity')
    Category = apps.get_model('pirateWarApp', 'Category')
    for i in range(1, 4):
        for l in range(1, 4):
            activity = Activity(category=Category.objects.get(pk=i), rewardGold=l * 10, rewardWood=l * 10,
                                rewardIron=l * 10, level=l,
                                duration=datetime.timedelta(minutes=0))
            activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pirateWarApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
        migrations.RunPython(create_activities)
    ]
