# Generated by Django 2.0.2 on 2018-02-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirateWarApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cannon',
            new_name='cannons',
        ),
    ]
