# Generated by Django 2.0.2 on 2018-04-02 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pirateWarApp', '0003_auto_20180328_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='endActivity',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
