# Generated by Django 2.0.2 on 2018-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirateWarApp', '0004_ship_endactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='endActivity',
            field=models.DateTimeField(default=None),
        ),
    ]
