# Generated by Django 2.0.2 on 2018-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirateWarApp', '0005_auto_20180402_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='endActivity',
            field=models.DateTimeField(null=True),
        ),
    ]
