# Generated by Django 2.0.2 on 2018-04-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirateWarApp', '0004_auto_20180404_1615'),
        ('pirateWarApp', '0007_ship_xp'),
    ]

    operations = [
    ]
